spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/one-plan
    username: one-plan
    password: one-plan
    pool:
      max-life-time: -1
    properties:
      sslMode: DISABLE
      sslRootCert:

  flyway:
    url: jdbc:postgresql://localhost:5432/one-plan
    enabled: true
    user: one-plan
    password: one-plan

api:
  base:
    url:
      oauth: http://localhost:9090
