---
# Per environment values which override defaults in hmpps-one-plan-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: one-plan-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    ENVIRONMENT: preprod
    OAUTH_BASE_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
