### Get an auth token from local docker hmpps-auth
POST http://localhost:9090/auth/oauth/token?grant_type=password&username=AUTH_USER&password=password123456
Authorization: Basic elite2apiclient clientsecret

> {% client.global.set("auth_token", response.body["access_token"]); %}

### Create a plan
POST {{base.url}}/person/123/plans
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "planType": "PERSONAL_LEARNING"
}

> {% client.global.set("planReference", response.body["reference"]); %}

### Get plan
GET {{base.url}}/person/123/plans/{{planReference}}
Authorization: Bearer {{auth_token}}

### Get all plans
GET {{base.url}}/person/123/plans
Authorization: Bearer {{auth_token}}

### Create objective
POST {{base.url}}/person/123/plans/{{planReference}}/objectives
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "title":"title",
  "targetCompletionDate": "2024-02-01",
  "status":"status",
  "note":"note",
  "outcome":"outcome"
}
> {% client.global.set("objectiveReference", response.body["reference"]); %}

### Get Objective
GET {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}
content-type: application/json
Authorization: Bearer {{auth_token}}

### Update objective
PUT {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "title":"title2",
  "targetCompletionDate": "2024-02-02",
  "status":"status2",
  "note":"note2",
  "outcome":"outcome2"
}
> {% client.global.set("objectiveReference", response.body["reference"]); %}
