### Get an auth token from local docker hmpps-auth
POST http://localhost:9090/auth/oauth/token?grant_type=password&username=ONE_PLAN_USER&password=password123456
Authorization: Basic elite2apiclient clientsecret

> {% client.global.set("auth_token", response.body["access_token"]); %}

### Get an auth token from dev
// @no-redirect
POST https://sign-in-dev.hmpps.service.justice.gov.uk/auth/sign-in
content-type: application/x-www-form-urlencoded

redirect_uri=&username={{authUser}}&password={{authPassword}}
> {%
    const cookie = response.headers.valueOf('Set-Cookie');
    const token = cookie.split(';')[0].split('=')[1]
    client.global.set("auth_token", token);
%}

### Create a plan
POST {{base.url}}/person/123/plans
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "planType": "PERSONAL_LEARNING"
}

> {% client.global.set("planReference", response.body["reference"]); %}

### Get plan
GET {{base.url}}/person/123/plans/{{planReference}}
Authorization: Bearer {{auth_token}}

### Get all plans
GET {{base.url}}/person/123/plans
Authorization: Bearer {{auth_token}}

### Create objective
POST {{base.url}}/person/123/plans/{{planReference}}/objectives
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "title":"title",
  "targetCompletionDate": "2024-02-01",
  "status":"IN_PROGRESS",
  "note":"note",
  "outcome":"outcome"
}
> {% client.global.set("objectiveReference", response.body["reference"]); %}

### Get Objective
GET {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}
content-type: application/json
Authorization: Bearer {{auth_token}}

### Update objective
PUT {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "title":"title2",
  "targetCompletionDate": "2024-02-02",
  "status":"COMPLETED",
  "note":"note2",
  "outcome":"outcome2",
  "reasonForChange": "The reason that it changed"
}
> {% client.global.set("objectiveReference", response.body["reference"]); %}

### Create Step
POST {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}/steps
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "description":"description",
  "status": "IN_PROGRESS",
  "staffTask": false
}
> {% client.global.set("stepReference", response.body["reference"]); %}

### Get Step
GET {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}/steps/{{stepReference}}
Authorization: Bearer {{auth_token}}

### Update Step
PUT {{base.url}}/person/123/plans/{{planReference}}/objectives/{{objectiveReference}}/steps/{{stepReference}}
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "description":"description2",
  "status": "COMPLETED",
  "staffTask": false,
  "reasonForChange": "2"
}
